# Generated by Django 5.2.1 on 2025-05-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='equipos.estado'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='tipo_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='equipos.tipoingreso'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='equipos.ubicacion'),
        ),
        migrations.CreateModel(
            name='EquiposMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField()),
                ('observaciones', models.CharField(max_length=100)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='equipos.equipos')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='equipos.ubicacion')),
            ],
        ),
    ]
